### ISSUE TITLE
Not a bug! Just a few questions

### ISSUE THREAD

**Issue by anoomolu** [AnOpenSauceDev/FastRandom#19]
Hiya! I've been using Faster Random for a while now, and the optimisations it makes seem really promising. Also appreciate the changelogs, I enjoy reading them :)

I was wondering if you've done any benchmarks when comparing with just Vanilla/standard optimisation suite? (thinking Sodium, Lithium, FerriteCore and Modernfix).

I really don't know much about Minecraft code, and wanted to know where Random is used most often/where FasterRandom would have the most impact. Worldgen is an obvious one, but apart from that I'm kinda clueless 😭 

Lastly, not really a question but I hope you have a lovely day!

**Comment by AnOpenSauceDev** [comment]
> I was wondering if you've done any benchmarks when comparing with just Vanilla/standard optimisation suite? (thinking Sodium, Lithium, FerriteCore and Modernfix).

I have done benchmarks before with Faster Random, and did display them, but the results aren't really something you can easily measure. When I say that the mod is "100X faster" I'm referring to the speed of **Faster Random generating a floating-point (basically a decimal) number vs. Vanilla.**

 Any performance gains from Faster Random **do stack with other performance mods**, because none of them really touch the RNG system (probably because of the vanilla-parity breaking cave changes).

>I really don't know much about Minecraft code, and wanted to know where Random is used most often/where FasterRandom would have the most impact. Worldgen is an obvious one, but apart from that I'm kinda clueless 😭

Random is used in **almost every part of the game,** that's stuff like particles, rod casting, entity movement, light flickering (yes, minecraft intentionally flickers all light sources), entity creation, some footstep logic, and much more.
