### ISSUE TITLE
What type of random is this?

### ISSUE THREAD

**Issue by Pop000100** [AnOpenSauceDev/FastRandom#3]
https://prng.di.unimi.it/ lists some of them. they have different performance and randomness.

**Comment by PoneyClairDeLune** [comment]
@AnOpenSauceDev How does this mod affect the gameplay? Will there be no noticeable difference with this mod enabled?

**Comment by AnOpenSauceDev** [comment]
> @AnOpenSauceDev How does this mod affect the gameplay? Will there be no noticeable difference with this mod enabled?

There shouldn't be too much of a difference in gameplay, but `ThreadLocalRandom` does deviate a bit from Minecraft's random due it generating its own "seed" and a few other technical differences on how they both work. That being said, both of these generators do have some level of variation on repeated runs, and i have tried to keep the methods used mostly the same, so that the game wont be _too_ different.

A few things affected (non-exhaustive) are:
- Block Drop physics
- Ender Dragon Breath _particles_ on the _client_
- possibly some types of loot drops from mobs
- fishing rod physics
- music delay before starting a new song
- wandering trader offers

again, i have to rephrase how little this actually changes from vanilla behaviour, especially because most of these are really small differences, for somewhat minor things.

**Comment by AnOpenSauceDev** [comment]
@PoneyClairDeLune 
Terrain generation (seemingly only with caves) is also affected, see #17. I'm assuming the different values are causing terrain to be shifted slightly.
