### ISSUE TITLE
[OTHER]: Curseforge Upload

### ISSUE THREAD

**Issue by chorbintime** [AnOpenSauceDev/FastRandom#57]
### Does an issue already cover this?

- [X] I have searched for any existing issues, and didn't find any.

### Issue description.

Hello!

I'm a developer for [Luna Pixel Studios](https://www.curseforge.com/members/lunapixelstudios/projects), and we will soon be including Faster Random in all of our modpacks over time as new modpack updates are released.

We saw massive performance boosts with Faster Random installed, and after I contacted Steve to implement #56, we no longer have any reason to not use your mod. 

While the mod's license does allow redistribution, I am hesitant to redistribute mods to millions of people without asking the author first. Curseforge's rewards program is very fruitful, and it'd bring a lot more eyes onto the project if you were to upload it on the bigger platform.       

I understand why authors wouldn't upload to Curseforge (trust me, we have plenty of reasons we wouldn't either), but Curseforge simply has a much larger userbase and it'd be a nice income stream in exchange for your work :p 

Thanks!

**Comment by AnOpenSauceDev** [comment]
Faster Random is [actually on CurseForge](https://www.curseforge.com/minecraft/mc-mods/faster-random), but I've been avoiding updating it due to the hassle of dealing with lots of issues from the JDK errors that will show up.

Now that's not really a problem, So I'm more than happy to upload the newest versions and update the artwork now.

**Comment by chorbintime** [comment]
That'd be great! Thank you so much

**Comment by AnOpenSauceDev** [comment]
Closing due to CurseForge release.
